adapter: mysql2
host:#используемый хост например: host: localhost
username:#ник пользователя mysql например: username: root
password:# пароль пользователя mysql например: password: 123
database: #к какой бд конектимся напримре: database: report_system_development

