adapter: mysql2
host: localhost #используемый хост например: host: localhost
username: root #ник пользователя mysql например: username: root
password: abc # пароль пользователя mysql например: password: 123
database: report_system_development #к какой бд конектимся напримре: database: report_system_development

