#!/usr/bin/env ruby
require "rubygems"
require "bundler/setup"
require "mailman"
Mailman.config.logger = Logger.new("log/mailman.log")

Mailman.config.pop3 = {
    server: 'pop.gmail.com', port: 995, ssl: true,
    username: 'yourprofspbsys@gmail.com', #между ' ' нужно написать email
    password: 'asKDe67wOvg'   #между ' ' нужно написать пароль от ящика
}


Mailman::Application.run do
  default do
    begin
      Client.receive_mail(message)
    rescue Exception => e
      Mailman.logger.error "Error:\n#{message}"
      Mailman.logger.error [e, *e.backtrace].join("\n")
    end
  end
end
